WINES = [
    {"Brand": "Vinho do Porto", "Year": 2015, "Price": 25.0, "Region": "Douro", "Description": "Um vinho fortificado, doce e encorporado", "Nutricion": "20%", "Supplier": 74354, "Stock": 23 },
    {"Brand": "Château Margaux", "Year": 2018, "Price": 450.0, "Region": "Bordeaux", "Description": "Elegante e encorpado, com notas de frutas vermelhas", "Nutricion": "14%", "Supplier": 33324, "Stock": 124 },
    {"Brand": "Penfolds Grange", "Year": 2020, "Price": 700.0, "Region": "Barossa Valley", "Description": "Frutas escuras e taninos sedosos", "Nutricion": "15%", "Supplier": 56257, "Stock": 85 },
    {"Brand": "Antinori Tignanello", "Year": 2019, "Price": 120.0, "Region": "Toscana", "Description": "Blend sofisticado com toques de baunilha", "Nutricion": "13.5%", "Supplier": 56458, "Stock": 320 },
    {"Brand": "Almaviva", "Year": 2021, "Price": 150.0, "Region": "Valle Central", "Description": "Notas de especiarias e frutas maduras", "Nutricion": "14.5%", "Supplier": 78589, "Stock": 215 },
    {"Brand": "Vega Sicilia Único", "Year": 2016, "Price": 500.0, "Region": "Ribera del Duero", "Description": "Vinho espanhol icônico com maturação longa", "Nutricion": "14%", "Supplier": 99876, "Stock": 78 },
    {"Brand": "Opus One", "Year": 2017, "Price": 350.0, "Region": "Napa Valley", "Description": "Aromas complexos de frutos vermelhos e carvalho", "Nutricion": "14.5%", "Supplier": 23342, "Stock": 90 },
    {"Brand": "Sassicaia", "Year": 2018, "Price": 250.0, "Region": "Bolgheri", "Description": "Notas minerais e taninos refinados", "Nutricion": "13.5%", "Supplier": 11129, "Stock": 180 },
    {"Brand": "Don Melchor", "Year": 2021, "Price": 120.0, "Region": "Maipo Valley", "Description": "Frutas negras e toque de chocolate amargo", "Nutricion": "14.5%", "Supplier": 44560, "Stock": 400 },
    {"Brand": "Montes Alpha M", "Year": 2021, "Price": 80.0, "Region": "Colchagua Valley", "Description": "Blend potente e equilibrado", "Nutricion": "15%", "Supplier": 34437, "Stock": 530 },
    {"Brand": "Barolo Riserva", "Year": 2017, "Price": 200.0, "Region": "Piemonte", "Description": "Aromas intensos e taninos marcantes", "Nutricion": "14%", "Supplier": 20215, "Stock": 150 },
    {"Brand": "Châteauneuf-du-Pape", "Year": 2019, "Price": 90.0, "Region": "Ródano", "Description": "Frutas vermelhas maduras com notas de especiarias", "Nutricion": "14%", "Supplier": 64278, "Stock": 275 },
    {"Brand": "Carmelo Patti", "Year": 2018, "Price": 60.0, "Region": "Mendoza", "Description": "Vinho argentino com notas de ameixas e cerejas", "Nutricion": "13.5%", "Supplier": 34438, "Stock": 350 },
    {"Brand": "Quinta do Crasto", "Year": 2020, "Price": 35.0, "Region": "Douro", "Description": "Vinho português robusto e aromático", "Nutricion": "14%", "Supplier": 76643, "Stock": 1900 },
    {"Brand": "Meerlust Rubicon", "Year": 2019, "Price": 50.0, "Region": "Stellenbosch", "Description": "Blend sul-africano com notas de cassis e tabaco", "Nutricion": "14.5%", "Supplier": 49802, "Stock": 500 },
    {"Brand": "Catena Zapata Adrianna", "Year": 2018, "Price": 180.0, "Region": "Mendoza", "Description": "Elegância e equilíbrio com toque mineral", "Nutricion": "14%", "Supplier": 94386, "Stock": 130 },
    {"Brand": "Clos Apalta", "Year": 2019, "Price": 200.0, "Region": "Colchagua Valley", "Description": "Frutas maduras e especiarias exóticas", "Nutricion": "15%", "Supplier": 12653, "Stock": 230 },
    {"Brand": "Torres Mas La Plana", "Year": 2020, "Price": 70.0, "Region": "Penedès", "Description": "Aromas florais e de frutas negras", "Nutricion": "14.5%", "Supplier": 42983, "Stock": 400 },
    {"Brand": "Beringer Private Reserve", "Year": 2018, "Price": 150.0, "Region": "Napa Valley", "Description": "Notas de cerejas pretas e mocha", "Nutricion": "15%", "Supplier": 54309, "Stock": 120 },
    {"Brand": "Croft Vintage Port", "Year": 2016, "Price": 120.0, "Region": "Douro", "Description": "Vinho do Porto de caráter intenso e encorpado", "Nutricion": "20%", "Supplier": 22200, "Stock": 300 },
    {"Brand": "Amarone della Valpolicella", "Year": 2017, "Price": 75.0, "Region": "Vêneto", "Description": "Notas de frutas secas e chocolate", "Nutricion": "15%", "Supplier": 31331, "Stock": 600 },
    {"Brand": "Lafite Rothschild", "Year": 2015, "Price": 1000.0, "Region": "Bordeaux", "Description": "Excepcional, com grande potencial de guarda", "Nutricion": "13.5%", "Supplier": 23987, "Stock": 50 },
    {"Brand": "Quinta do Vallado", "Year": 2020, "Price": 45.0, "Region": "Douro", "Description": "Frutas maduras e taninos macios", "Nutricion": "14%", "Supplier": 75543, "Stock": 320 },
    {"Brand": "Luís Pato Vinha Pan", "Year": 2019, "Price": 35.0, "Region": "Bairrada", "Description": "Vinho português com notas terrosas e florais", "Nutricion": "13.5%", "Supplier": 12410, "Stock": 410 },
    {"Brand": "Altas Quintas Reserva", "Year": 2021, "Price": 25.0, "Region": "Alentejo", "Description": "Notas de frutas negras e especiarias doces", "Nutricion": "14%", "Supplier": 64367, "Stock": 500 },
    {"Brand": "Concha y Toro Don Melchor", "Year": 2018, "Price": 150.0, "Region": "Maipo Valley", "Description": "Elegante e encorpado com notas de carvalho", "Nutricion": "14.5%", "Supplier": 32823, "Stock": 230 },
    {"Brand": "Bouchard Père et Fils", "Year": 2019, "Price": 300.0, "Region": "Borgonha", "Description": "Vinho branco complexo e sofisticado", "Nutricion": "13%", "Supplier": 47656, "Stock": 180 },
    {"Brand": "Niepoort Vintage Port", "Year": 2017, "Price": 140.0, "Region": "Douro", "Description": "Clássico e estruturado, perfeito para guarda", "Nutricion": "20%", "Supplier": 62172, "Stock": 280 },
    {"Brand": "Very Old Single Harvest Port", "Year": 1964, "Price": 250.0, "Region": "Porto", "Description": "Clássico e estruturado, perfeito para guarda", "Nutricion": "20%", "Supplier": 62172, "Stock": 280 },
    {"Brand": "Quinta da Leda", "Year": 2018, "Price": 50.0, "Region": "Douro", "Description": "Frutas vermelhas maduras com taninos suaves", "Nutricion": "14%", "Supplier": 81192, "Stock": 450 },
    {"Brand": "Marchesi Antinori Guado al Tasso", "Year": 2020, "Price": 120.0, "Region": "Bolgheri", "Description": "Notas de especiarias e final longo", "Nutricion": "13.5%", "Supplier": 35348, "Stock": 250 },
    {"Brand": "Gaja Barbaresco", "Year": 2017, "Price": 250.0, "Region": "Piemonte", "Description": "Taninos refinados e notas de frutas escuras", "Nutricion": "14%", "Supplier": 20866, "Stock": 100 },
    {"Brand": "Corton-Charlemagne Grand Cru", "Year": 2019, "Price": 350.0, "Region": "Borgonha", "Description": "Mineralidade e acidez marcantes", "Nutricion": "13%", "Supplier": 72001, "Stock": 60 },
    {"Brand": "Tenuta San Guido Guidalberto", "Year": 2021, "Price": 55.0, "Region": "Toscana", "Description": "Blend elegante e macio", "Nutricion": "13.5%", "Supplier": 39292, "Stock": 500 },
    {"Brand": "Taittinger Comtes de Champagne", "Year": 2012, "Price": 180.0, "Region": "Champagne", "Description": "Champagne refinado com bolhas persistentes", "Nutricion": "12.5%", "Supplier": 81200, "Stock": 150 },
    {"Brand": "Krug Grande Cuvée", "Year": "2001", "Price": 300.0, "Region": "Champagne", "Description": "Complexidade e elegância únicas", "Nutricion": "12%", "Supplier": 40201, "Stock": 110 },
    {"Brand": "Petrus", "Year": 2016, "Price": 3500.0, "Region": "Bordeaux", "Description": "Um dos maiores ícones do mundo do vinho", "Nutricion": "14%", "Supplier": 99911, "Stock": 15 },
    {"Brand": "Errazuriz Don Maximiano", "Year": 2018, "Price": 100.0, "Region": "Aconcagua Valley", "Description": "Elegante com notas de frutas vermelhas", "Nutricion": "14.5%", "Supplier": 32556, "Stock": 180 },
    {"Brand": "Casanova di Neri Brunello", "Year": 2017, "Price": 120.0, "Region": "Toscana", "Description": "Encantador e estruturado com notas de cereja", "Nutricion": "14%", "Supplier": 31250, "Stock": 300 },
    {"Brand": "Joseph Phelps Insignia", "Year": 2018, "Price": 300.0, "Region": "Napa Valley", "Description": "Blend icônico com notas de baunilha", "Nutricion": "15%", "Supplier": 56668, "Stock": 75 },
    {"Brand": "Domaine Leflaive Puligny-Montrachet", "Year": 2019, "Price": 250.0, "Region": "Borgonha", "Description": "Vinho branco elegante e complexo", "Nutricion": "13%", "Supplier": 35527, "Stock": 120 },
    {"Brand": "Taylor's Vintage Port", "Year": 2016, "Price": 150.0, "Region": "Douro", "Description": "Porto clássico com potencial de guarda", "Nutricion": "20%", "Supplier": 81221, "Stock": 200 },
    {"Brand": "Fonseca Bin 27", "Year": "2001", "Price": 30.0, "Region": "Douro", "Description": "Doce e frutado, perfeito para sobremesas", "Nutricion": "20%", "Supplier": 41125, "Stock": 100 }
]
